default_platform(:android)

platform :android do
  desc "Upload AAB to Google Play internal track"
  lane :deploy do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: "draft",
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end
end
